application: tririver-1250
version: 1_0_2
runtime: python27
api_version: 1
threadsafe: yes

default_expiration: "2d 12h"

# google manul scaling
# google default this to 10, max number is 100
# automatic_scaling:
#   max_concurrent_request: 20

handlers:
- url: /_ah/mail/.+
  script: handle_catchall.app
- url: /images
  static_dir: static/images
- url: /css
  static_dir: static/css
  # expiration: "1h"
- url: /.*
  script: tririver.application


libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"

inbound_services:
- mail
# - warmup
