application: market-175515
version: 1_0_0
runtime: python27
api_version: 1
threadsafe: yes

default_expiration: "2d 12h"

# google manul scaling
# google default this to 10, max number is 100
# automatic_scaling:
#   max_concurrent_request: 20

handlers:
- url: /images
  static_dir: static/images
- url: /css
  static_dir: static/css
  # expiration: "1h"
- url: /.*
  script: main.application


libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: markupsafe
  version: "0.15"